apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: production-redis
            namespace: redis-sentinel
            server: https://cluster-production:1234
          - name: staging-redis
            namespace: redis-sentinel
            server: https://cluster-staging:1234
          - name: development-redis
            namespace: redis-sentinel
            server: https://cluster-development:1234
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: tools
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: redis
        targetRevision: 20.2.1
        helm:
          releaseName: redis
          parameters:
            #Auth
            - name: auth.enabled
              value: "false"
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
